//NORMAL AUTHENTICATION
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';


// FACEBOOK AUTHENTICATION
export const FACEBOOK_AUTH_START = 'FACEBOOK_AUTH_START';
export const FACEBOOK_AUTH_SUCCESS = 'FACEBOOK_AUTH_SUCCESS';
export const FACEBOOK_AUTH_FAIL = 'FACEBOOK_AUTH_FAIL';

// RIDES ACTIONS
export const FETCH_RIDES_START = 'FETCH_RIDES_START';
export const FETCH_RIDES_FAIL = 'FETCH_RIDES_FAIL';
export const FETCH_RIDES_SUCCESS = 'FETCH_RIDES_SUCCESS';


// SINGLE RIDE ACTIONS
export const FETCH_RIDE_START = 'FETCH_RIDE_START';
export const FETCH_RIDE_FAIL = 'FETCH_RIDE_FAIL';
export const FETCH_RIDE_SUCCESS = 'FETCH_RIDE_SUCCESS';


// SOCKET CONNECTION TYPES
export const WS_CONNECT_START = 'WS_CONNECT';
export const WS_CONNECT_FAIL = 'WS_CONNECT_FAIL';
export const WS_CONNECT_SUCCESS = 'WS_CONNECT_SUCCESS';

export const WS_DISCONNECT = 'WS_DISCONNECT';


export const WS_MESSAGE = 'WS_MESSAGE';
// REQUESTS THROUGH SOCKETS
export const GET_MY_REQUESTS = 'GET_MY_REQUESTS';
export const GET_RIDE_REQUESTS = 'GET_RIDE_REQUESTS';


// JOIN REQUEST
export const JOIN_REQUEST = 'JOIN_REQUEST';
export const JOIN_REQUEST_START = 'JOIN_REQUEST_START';
export const JOIN_REQUEST_FAIL = 'JOIN_REQUEST_FAIL';
export const JOIN_REQUEST_SUCCESS = 'JOIN_REQUEST_SUCCESS';

// Update RequestsofRides
export const ADD_REQUESTS_OF_RIDES = 'ADD_REQUESTS_OF_RIDES';
export const REMOVE_REQUESTS_OF_RIDES = 'REMOVE_REQUESTS_OF_RIDES';


// Update Requests
export const REMOVE_REQUESTS = 'REMOVE_REQUESTS';
// UPDATE REQUESTS STATUS
export const UPDATE_REQUESTS = 'UPDATE_REQUESTS';



// UNJOIN
export const UNJOIN_START = 'UNJOIN_START';
export const UNJOIN_FAIL = 'UNJOIN_FAIL';
export const UNJOIN_SUCCESS = 'UNJOIN_SUCCESS';
export const UNJOIN = 'UNJOIN';

// DECLINE JOIN
export const DECLINE_JOIN = 'DECLINE_JOIN';

// ACCEPT JOIN
export const ACCEPT_JOIN = 'ACCEPT_JOIN';



export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const DECLINE_REQUEST = 'DECLINE_REQUEST';


// NOTIFICATIONS ACTIONS
export const SET_READ = 'SET_READ';
export const SET_ALL_READ = 'SET_ALL_READ';
export const RECEIVE_NOTIFICATION = 'RECEIVE_NOTIFICATION';





export const GET_USER_START = "GET_USER_START";
export const GET_USER_FAIL = "GET_USER_FAIL";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";


